c : KeyLogger.c
	cl.exe KeyLogger.c

cpp : KeyLogger.cpp
	cl.exe /EHsc KeyLogger.cpp

go : KeyLogger.go
	go build KeyLogger.go

clean : KeyLogger.exe
	del KeyLogger.exe
	del KeyLogger.obj
	del Intercept.txt

default : c
